server:
  port: 2225
  servlet:
      # 项目contextPath
    context-path: /
  tomcat:
      # tomcat的URI编码
    uri-encoding: UTF-8
      # tomcat最大线程数，默认为200
    max-threads: 800
      # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
spring:
  application:
    name: rtmedia_biz
    description: 实时文件服务
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    druid:
      master: # 基础数据库，默认主库
        url: jdbc:oracle:thin:@//127.0.0.1:1521/xe
        username: LSDB
        password: Lsdb$sys
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: oracle.jdbc.OracleDriver
        # 初始连接数
        initial-size: 10
        # 最大连接池数量
        max-active: 100
        # 最小连接池数量
        min-idle: 10
        # 配置获取连接等待超时的时间
        max-wait: 60000
        # 打开PSCache，并且指定每个连接上PSCache的大小
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: false
        test-on-return: false
      cluster:
        - key: slave1 #业务库1，从库1
          url:
          idle-timeout: 20000
          username:
          password:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name:
          # 初始连接数
          initial-size: 10
          # 最大连接池数量
          max-active: 100
          # 最小连接池数量
          min-idle: 10
          # 配置获取连接等待超时的时间
          max-wait: 60000
          # 打开PSCache，并且指定每个连接上PSCache的大小
          pool-prepared-statements: true
          max-pool-prepared-statement-per-connection-size: 20
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false

mybatis:
  type-aliases-package: com.zyd.sop.biz
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml
#日志配置
logging:
  level:
    com.njzyd.thlsdb: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

